# Generated by Django 4.2.7 on 2024-01-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
