# Generated by Django 4.2.7 on 2024-01-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_app', '0002_detailsmodel_image_alter_detailsmodel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
